name: Jira Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  jira-pr:
    permissions:
      pull-requests: write
      contents: read
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add Jira ticket to PR title / add link to PR description
        uses: onrunning/jira-pr-action@v2
        with:
          jira-account: java-mp
          ticket-regex: '^[A-Z]+-\d+'